apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app
        image: utibeabasi6/argocd-code:v1.0.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

